pool:
  name: Hosted Mac Internal

variables:
- name: BuildPlatform
  value: Any CPU
- name: BuildConfiguration
  value: DebugNoGui

steps:

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'Mono.Addins.sln'
    feedsToUse: 'select'

- task: MSBuild@1
  displayName: 'Build solution Mono.Addins.sln'
  inputs:
    solution: Mono.Addins.sln
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: MSBuild@1
  displayName: 'Test Assemblies Test\UnitTests\bin\Debug\UnitTests.dll'
  inputs:
    solution: 'Test\UnitTests\UnitTests.csproj'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/t:Test'

- task: PublishTestResults@2
  displayName: 'Publish Test Results Test\UnitTests\bin\Debug\*.xml'
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: 'Test\UnitTests\bin\Debug\*.xml'

- task: CopyFiles@1
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)\bin'
    Contents: '*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

